### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by JacoAnnandale** [jackkitley/geyserwise_max_iot#1]
Thank you for this. Been waiting long for this integration

Can you please elaborate on the Panel and the modification for the ESP8266.

Can find the IOT Panel on their website, have you got more info

**Comment by jackkitley** [comment]
@JacoAnnandale Hello

1. I replaced the wifi module that came with the IoT panel. The original module was tied to Tuya and was not flashable. I bought this https://www.robotics.org.za/ESP-12F to replace it.
2. I uploaded firmware and then simply replaced with a heat gun.

Geyserwise can be contacted. They have the panels available.

**Comment by JacoAnnandale** [comment]
Thanks a lot

 

Just for interest sake, how did you get the data from the panel ? Did you use some kind of “bus monitor”, oscilloscope  or logic analyzer.?

 

I tried with Logic analyzer and small scope (to slow), but could not get it working.

 

 

Have a great one

**Comment by jackkitley** [comment]
@JacoAnnandale Just a UART monitoring TX/RX
