### ISSUE TITLE
Solar Pump Status

### ISSUE THREAD

**Issue by BigFan00777** [jackkitley/geyserwise_max_iot#2]
Hi Jackkitley
Thank you so much for your MQTT solution for Geyserwise MAX IoT. 
I replaced the Wifi Module and all works fine. 
Just a question/request, please.
I would like to monitor the Solar Pump Status as well. With the "Tuya WiFi Module" this was possible.
Any idea how I could go about it?

**Comment by jackkitley** [comment]
@BigFan00777 hey bud

Are you actually using it on your panel?

I would love to do the pump reading. I sat for hours trying to find it in amongst the HEX values....

Looking for it switching on and off as it only does it when you hit holiday mode and when the solar diff has been met.

**Comment by BigFan00777** [comment]
Yes. I am using on my panel. My solar geyser has a pump that circulates the heated water. Unfortunately my solar geyser has a syphering problem - at night the geyser water is circulated back (by itself - no pump is involved) to the collector to warm it (this has nothing to do with the freezing setting).  Despite of many "heat traps" in the piping, it still happens. So they had to install a solenoid to close off the flow - This solenoid opens when the pump switches on and stays open for an hour after the last pump trigger.

Sorry for the long explanation - but that is my issue.

Not a big problem as I can do the calculations myself. Just thought it would have been great to have the Solar Pump Status.

Great work by the way - I also decoded my Paradox Alarm codes +/- 17 years ago ;-)

**Comment by jackkitley** [comment]
Yes. Me as well. I had the issue for 6 years because installed incorrectly.
Through HA data I noticed it and fixed it...

**Comment by jackkitley** [comment]
> Yes. I am using on my panel. My solar geyser has a pump that circulates the heated water. Unfortunately my solar geyser has a syphering problem - at night the geyser water is circulated back (by itself - no pump is involved) to the collector to warm it (this has nothing to do with the freezing setting). Despite of many "heat traps" in the piping, it still happens. So they had to install a solenoid to close off the flow - This solenoid opens when the pump switches on and stays open for an hour after the last pump trigger.
> 
> Sorry for the long explanation - but that is my issue.
> 
> Not a big problem as I can do the calculations myself. Just thought it would have been great to have the Solar Pump Status.
> 
> Great work by the way - I also decoded my Paradox Alarm codes +/- 17 years ago ;-)

You fix the issue with a non return valve. There should be two.

**Comment by jackkitley** [comment]
1. I'll look for pump active and add in. 
2. On initial power on after loadshedding there isn't a mqtt push with data when Temps are static. I'll fix as well

**Comment by BigFan00777** [comment]
"You fix the issue with a non return valve. There should be two."
Believe me - 2 x NRVs are also installed - this system is mind-boggling. It defeats all Laws of Physics. Einstein would have had a heart attack! LOL! At the end of the day, the only solution was a solenoid valve.

Thank you for all your efforts. Any chance of including updates OTA (or is it possible already)?

**Comment by jackkitley** [comment]
> "You fix the issue with a non return valve. There should be two." Believe me - 2 x NRVs are also installed - this system is mind-boggling. It defeats all Laws of Physics. Einstein would have had a heart attack! LOL! At the end of the day, the only solution was a solenoid valve.
> 
> Thank you for all your efforts. Any chance of including updates OTA (or is it possible already)?

There is the ability got OTA firmware upload via interface if that's what you want?

**Comment by jackkitley** [comment]
![19c7df2ff6e08e8f0023bca099860e5e15098f41_2_450x1000](https://user-images.githubusercontent.com/3243014/208231266-27dc50dc-c280-4bbf-adc4-45f7d06a2597.jpeg)

**Comment by BigFan00777** [comment]
Great! Thanks. I presume to revert it to an AP again, I have to send the command: cmnd/geyser/wifi ?
Can the update be an .ino file or must it be a .bin file?

**Comment by jackkitley** [comment]
> Great! Thanks. I presume to revert it to an AP again, I have to send the command: cmnd/geyser/wifi ? Can the update be an .ino file or must it be a .bin file?

To revert to AP you reset it. It only accepts a bin but remember if you get it wrong you could prevent connect.

**Comment by jackkitley** [comment]
Erase I mean. Will send back to AP which you will need to connect to via phone or laptop to configure wifi and mqtt

**Comment by jackkitley** [comment]
> Great! Thanks. I presume to revert it to an AP again, I have to send the command: cmnd/geyser/wifi ? Can the update be an .ino file or must it be a .bin file?

This command I put in place incase of emergency

**Comment by BigFan00777** [comment]
Thank you Jack
I did not solder my Wifi Module onto the board again. I did however solder pins which I connect to my Wifi Module with wires so I can program it via the Arduino GUI.  I will solder it whenever everything is working fine.

**Comment by jackkitley** [comment]
> Great! Thanks. I presume to revert it to an AP again, I have to send the command: cmnd/geyser/wifi ? Can the update be an .ino file or must it be a .bin file?

I forgot to mention that you can also reset the device by combination of button pushing on the panel. So in total there are 3 ways to reset to AP

**Comment by BigFan00777** [comment]
Hi Jack
I managed to find the Pump Status. I see that the Pump Status changes when in Holiday Mode as well - I wonder why?
Nevertheless, when the Collector Temp and Geyser Temp Difference is met, the Pump Status changes.

110102401110204000451340102050200101401`1`102204000710320400040104204000401052040005010620400050107204000510820400052 – Pump on
110102401110204000451340102050200101401`0`102204000710320400040104204000401052040005010620400050107204000510820400050– Pump off
110102401110204000451340102050200101401`1`102204000710320400040104204000401052040005010620400050107204000510820400052– Pump on
110102401110204000451340102050200101401`0`102204000710320400040104204000401052040005010620400050107204000510820400049– Pump off

**Comment by jackkitley** [comment]
@BigFan00777 fantastic. Well done  I haven't had time to sit and look. Yes. When in holiday mode it activates as mentioned above by me.

"Looking for it switching on and off as it only does it when you hit holiday mode and when the solar diff has been met."

I'll add to the code and add to mqqt and will then push a new bin .

**Comment by BigFan00777** [comment]
Thank you
Note: The above traces are with Holiday Mode = off

**Comment by jackkitley** [comment]
@BigFan00777 ok noted but that shouldnt matter. Ill check my data along with yours.

Ill just log the change and send via MQTT

**Comment by jackkitley** [comment]
@BigFan00777 How did you get the output data string? Not hex.

https://github.com/jackkitley/geyserwise_max_iot/blob/main/geyser_read

**Comment by BigFan00777** [comment]
In your .ino code "bool readCommand() Procedure", I added the following:

    if (command_.length <= TUYA_MAX_LEN)
    {
      Serial.readBytes(command_.value, command_.length);

      //      Serial.println("RX_RAW:");
      //      for (size_t i = 0; i < command_.length; i++)
      //      {
      //        Serial.println(command_.value[i]);
      //      }
            if (command_.length > 2)
            {
                 String message = "Raw:";    //140111022040007
                 for (int i = 0; i < command_.length; i++)
                 {
                   message += command_.value[i];
                 }
                 if ( message != prev_message ) 
                 {
                    if (message.indexOf("140111022040007") > 0) {pump = 1;} else {pump = 0;};       //140101022040007 = Pump Off
                    client.publish(pump_topic, pump ? "ON" : "OFF");
                    client.publish(rawblock1_topic, toCharArray(message));
                 }
                 prev_message = message;
            }

and then publish it via MQTT to HA

**Comment by BigFan00777** [comment]
Error in my code: Removed the last "7"

if (message.indexOf("14011102204000") > 0) {pump = 1;} else {pump = 0;};       //14010102204000 = Pump Off

**Comment by jackkitley** [comment]
@BigFan00777 when I wrote the code it was cold and pump wasn't that active. I'll debug and get the hex to decimal position.

**Comment by jackkitley** [comment]
@BigFan00777 it's a 0 and a 1 I need to locate

**Comment by BigFan00777** [comment]
Hey Jack - I've got it working beautifully. Thanks again for the original .ino code. Great Job! I modified it for my purposes - I included IP, Mac and time as I use it in my HA

PS: Happy New Year!

**Comment by jackkitley** [comment]
@BigFan00777 ok. I see that it's at index position 

command_.value[33];

So you just need to work on this. You don't need to do a indexOf search.

I'm testing now. Will upload new code towards weekend when weather better.

**Comment by BigFan00777** [comment]
Thank you Jack!

**Comment by jackkitley** [comment]
> Thank you Jack!

Better weather today. Seems to be working.

![Screenshot_20230106-113758_Chrome](https://user-images.githubusercontent.com/3243014/210973930-ed9b794a-0c9b-49fd-a008-2e2fe5157ed5.jpg)

**Comment by jackkitley** [comment]
> Thank you Jack!

Repository updated with new code 

![Screenshot_20230108-105448_Chrome](https://user-images.githubusercontent.com/3243014/211188058-35f85447-53b4-4c8b-b9bd-d4b188be6b36.jpg)

**Comment by jackkitley** [comment]
Added pump status
