### ISSUE TITLE
Getting back into AP mode

### ISSUE THREAD

**Issue by Rudis1261** [jackkitley/geyserwise_max_iot#4]
Hi Jack,

First off thanks for taking the time to create this! I was wondering, I am busy flashing the code to my surrogate Wemos D1 mini. But how can I get back to the admin (AP) interface should I need to re-flash it remotely?

I know the geyserwise max when you hold the heating button I think it goes into discovery mode. Does this leverage that as well?

Cheers,
Rudi

**Comment by Rudis1261** [comment]
Ahhh I see, once it can connect to the MQTT server, it shows the wifi manager once more. I think it could be nice if it always is available if wifi is available. If my MQTT server goes away for any reason, this would be painful to get back.

**Comment by Rudis1261** [comment]
Working like a bomb otherwise. Will be sending some PRs for updating the docs and helping people getting started

**Comment by jackkitley** [comment]
@Rudis1261 Howdy!

Glad it worked.

1. You can hold the up arrow(yellow) for 3 seconds to reset to AP mode.
2. You can also send a reset topic to reset to AP mode. 

So if you publish to this topic it should receive and reset.

`if (strcmp(topic, "cmnd/geyser/wifi") == 0) {
      wifiManager.resetSettings();
      ESP.restart();
    }`

**Comment by Rudis1261** [comment]
That's awesome stuff man, thanks for taking the time to create this to save us from the evil cloud 🥴
